### ISSUE TITLE
Enhancement: Would be great to show the number of cookies blocked over the extension icon

### ISSUE THREAD

**Issue by TheGoddessInari** [craigmiskell/cookiemaster#1]
First of all, love the extension. It seems to work great.
Other addons that block or add things present a number over the icon to show how many things blocked, for instance. Could we get this for cookiemaster?

**Comment by craigmiskell** [comment]
Good idea.  I'm hoping to spend some time on CookieMaster these holidays, so I'll see what I can do

**Comment by craigmiskell** [comment]
Having just finished up the work on https://github.com/craigmiskell/cookiemaster/issues/7 I've come to realise that this request isn't going to be able to work well in the space remaining available, now that there are indicator dots, which I think are a lot more immediately useful.

Sorry to disappoint, but I have decided not to implement this.
