### ISSUE TITLE
the use of eval might be blocked by CSP policies

### ISSUE THREAD

**Issue by maxlath** [craigmiskell/cookiemaster#14]
any website that has a [`Content-Security-Policy` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) not whitelisting `unsafe-eval` would block the execution of the [`eval` code](https://github.com/craigmiskell/cookiemaster/blob/db7719e/content.js#L141-L162)

**Comment by craigmiskell** [comment]
Yes, as noted in https://github.com/craigmiskell/cookiemaster/issues/12

I have worked around it to the degree currently possible with release 1.1.3, by capturing the cookies after the fact with the cookieChanged event.  

Is there some specific action you wanting to suggest regarding this?

**Comment by maxlath** [comment]
oups, sorry, that's a duplicated issue then

**Comment by craigmiskell** [comment]
FYI: Released 1.1.4 with better CSP handling (uses a script tag, and adds a sha-sum CSP directive to any CSP headers)
