### ISSUE TITLE
Permission indicator disappears

### ISSUE THREAD

**Issue by ArcticGems** [craigmiskell/cookiemaster#17]
@craigmiskell 
I haven't been home for a while, so I just notice it today.

When I do this with cookiemaster 1.1.4, the permission indicator disappears for the site =

1. Allow first party cookies a site.
2. Disable first party cookies a site.

When this happens, I tried these steps and it didn't fix it =

1. Refresh
2. Close tab->Open new tab->Go to site again->Refresh
3. Restart Firefox->Refresh the site

See screenshot for how it is with one of these sites=
https://i.ibb.co/kKwThPz/cookie-Error01.jpg

**Comment by craigmiskell** [comment]
1.1.4 only got released yesterday, and it changed how the content script gets injected to capture cookies set by javascript.  It's quite likely there's something not working with that new approach.

But: it works fine for me on anime-planet.com (cookies are blocked and the indicator shows correctly) and interestingly many of the cookies are set by headers, and nothing about that code changed in 1.1.4 (just cookies set by Javascript).  Maybe there's some unexpected interaction with one of your other extensions.

Some logs might help; with as few browser tabs open as possible, could you open a fresh tab, click on the cookiemaster icon and then click Logs.  In the Logging Level dropdown at the top, select 'DEBUG".  Then in your fresh tab navigate to a problem site like anime-planet.com.  Once it has loaded, copy/paste the logs from the log window and email them to me (there may be slightly sensitive information in them and a public issue is probably not the right place to attach them directly).

**Comment by ArcticGems** [comment]
@craigmiskell 
Sent the debug log to your email you have on your mozilla addon page.

**Comment by craigmiskell** [comment]
Hmmm, that's practically silent, suggesting cookiemaster isn't getting a chance to do anything.  I have nothing firm to go on, but feels like either a bug that causes an exception so early on nothing much can process (but weirdly, is fine on e.g. github.com), or else one of your other extensions is getting involved in some fashion that causes grief (or a combination of both :))

Could you please:
1. Tell me what version of firefox you're using
1. Tell me what other extensions you have (particularly privacy/security type ones)
1. Try cookiemaster in a firefox profile with no other extensions.  Goto "about:profiles", create a new profile, click 'Launch profile in new browser' then add cookiemaster to that profile.  Then visit the problem sites and see if cookiemaster works as expected.  If it does, it's some interaction with your other extensions
1. Optional: Send me the logs again, but this time at TRACE level.  This is a firehose of data (if cookiemaster is working), and definitely contains sensitive information like cookie values (if any) from headers, so you'd want to have firefox only open with the problem site (nothing else at all, in any tab, while collecting logs).   If you'd rather not, I'm fine with that too, if you'd just like to turn it on and have a look for anything obviously wrong.  I'd be very interested in the first few lines after 'beforeNavigate with frameId X; clearing tabInfo', if they look safe to send.

**Comment by ArcticGems** [comment]
@craigmiskell 
1. FF 75.0
2. uBlock origin, NoScript, Ghostery, Smart HTTPS, ClearURLs
3-4. Will do when I get home again later.

Went to 'Firefox options>Privacy & Security>Cookies and Site Data>Manage Data...' and removed site data for anime-planet.com and after a refresh the indicator came back. 

When I do the same thing again as in https://github.com/craigmiskell/cookiemaster/issues/17#issue-602534529, the permission indicator disappears again.

**Comment by craigmiskell** [comment]
I managed to replicate the problem, and it seems to be uBlock origin that triggers it.  Once there is a cookie *stored* the set-cookie header is removed before cookiemaster gets a chance to see it.  From a *very* brief search through the code for uBlock, I couldn't see exactly where, but with extra logging it was very clear that the header was simply missing.  It's also (very slightly) possible that the website is behaving differently, but that seems rather unlikely.

So it's not a bug in cookiemaster; it's doing exactly what it is asked to do, given the data it is seeing (no cookie headers), and there's no code changes that could be made to make it behave differently.

On the plus side:   you're not getting any cookies from this site :)
