### ISSUE TITLE
DuckDuckGo preferred language cannot be set when cookies are blocked in cookiemaster

### ISSUE THREAD

**Issue by craigmiskell** [craigmiskell/cookiemaster#19]
VIsiting https://duckduckgo.com/settings and attempting to change the language while cookies are blocked for that domain causes the page to reload and no language preferences to be saved.

**Comment by craigmiskell** [comment]
@baptx FYI

**Comment by craigmiskell** [comment]
Actually this isn't specific to cookiemaster.

In a fresh firefox profile, without cookiemaster installed, if I go to about:preferences#privacy, click "Manage Permissions" under "Cookies and Site Data" and add duckduckgo.com with status 'Block', I get the same behaviour as when cookies for duckduckgo.com are blocked by cookiemaster.

This is simply how duckduckgo.com behaves when cookies cannot be set.

**Comment by baptx** [comment]
@craigmiskell it is possible to change the language with Firefox cookies disabled on a DuckDuckGo search page, for example https://duckduckgo.com/?q=test (not in the settings page, which does not have a fallback when cookies are disabled).
The issue only happened when blocking cookies with your addon.

**Comment by craigmiskell** [comment]
I assume you mean changing the language from the search result screen means clicking the "settings" dropdown below the search bar on the right, then clicking and selecting an option from the language dropdown.

In a clean profile:
* In default state, without cookie-master: this works, and sets a cookie
* With duckduckgo.com blocked in Firefox's settings, and without cookie-master: this does not work; the page reloads, and the language remains as the Browser Preferred Language.  It behaves exactly the same as when cookie-master is blocking the cookies.  

I cannot replicate a situation where it falls back to some other way of specifying the language (URL parameters, I assume).

Please describe, starting from a fresh profile, exactly how you see that fallback happening, where it saves/applies a language setting when cookies are blocked by firefox.

**Comment by baptx** [comment]
@craigmiskell no, I mean changing language should work with cookies disabled by clicking on the switch on the left of the country displayed, for example "France" in the screenshot attached below (this will use a URL parameter `kl=fr-fr` like I mentioned in the original issue).

![duckduckgo_change_language](https://user-images.githubusercontent.com/3785220/79839353-b0b18f80-83b4-11ea-8b80-b1969e6effa6.png)

That's the fastest way to change language on DuckDuckGo, no need to go in settings (I did not even know it was possible to change the language in settings, the language switch is what most people notice first).

Note: the language switch is used to change the language of the search results, not the language of DuckDuckGo user interface.

**Comment by craigmiskell** [comment]
Interesting; for me that shows a toggle for 'New Zealand'; it sets a 'kl' parameter in the URL, but also seems to select the search *results* to be more country specific (not exactly a language choice, although that's part of it).  For future bug reports please be extremely specific about what you do, click, and see.  It is really frustrating to try and debug something where you're assuming I know what you're seeing and thinking.

Thing is, that toggle works fine for me, with cookie-master installed and blocking cookies for duckduckgo.com.  I expect it's one of your other extensions.  Are you able to replicate this in a fresh clean profile with only cookie-master installed?

**Comment by baptx** [comment]
@craigmiskell I am using a clean profile with cookie-master addon installed only. To reproduce the problem, you first have to allow cookies on DuckDuckGo with your addon, then enable or disable the language switch and then disable cookies on DuckDuckGo with your addon. Now you will be able to reproduce the bug when trying to click on the language switch.
I explained it in this comment also: https://github.com/craigmiskell/cookiemaster/issues/15#issuecomment-613465157

Update: when we reload the page with cookies disabled, we can see in the web console that previous cookies (created when cookies were enabled) are still sent in the request header. The issue can probably be fixed by clearing the JavaScript variable `document.cookie` when we disable cookies with the addon.

**Comment by craigmiskell** [comment]
This is working as I intended then.  cookie-master only prevents cookies from being *set*.  If you allow that to happen, a cookie exists in the browser; if you then prevent that from happening in future, the cookie that was previously stored remains there.   cookie-master will allow any *deletes* to be processed regardless of the user configuration, but in this case the presence of the cookie from previous setting makes duckduckgo assume certain things (I guess).

In my opinion it is a step too far for cookie-master to actively delete cookies when the policy is changed.  That is best left to the user either through the existing firefox UI, or from another extension dedicated to deleting/editing cookies.

**Comment by baptx** [comment]
@craigmiskell I would have expected a cookie blocker addon to have the same behaviour as when blocking cookies through Firefox UI (no cookies stored or accessible anymore and no cookie sent on HTTP requests). So I will have to find another addon or patch uMatrix then.

Note: if you don't want to delete cookies, it may be possible to just override `document.cookie` (or keep a backup of the value) like what you did for `navigator.cookieEnabled`. It looks like that is the behaviour of Firefox cookie blocking, the cookie is still here but not accessible anymore from JavaScript (and of course not sent in HTTP requests).
