### ISSUE TITLE
Feature request: Show a "cookies allow/session/deny" little confirmation dialog that pops-up the first time a new domain is visited

### ISSUE THREAD

**Issue by smihaila** [craigmiskell/cookiemaster#21]
Remeber that "Ask" cookie option that was long time ago in Firefox, until approx version 50'ish? And which Mozilla, along with other Firefox forks like Pale Moon, has blatantly decided that "it didn't make sense anymore" and hence has removed it?

I enjoyed that option A LOT. It fitted my way of working and visiting web sites perfectly.
It worked like this: the very first time when you visited a domain, it would show a little pop-up dialog with 3 (three) options: (1) Allow, (2) Allow for session, or (3) Deny. And a checkbox would also control whether or not you want your choice/decision to apply for any sub-domain as well. Plus a button to see domain/cookie details.

Here's a screen shot of that little pop-up dialog, taken from a version of Pale Moon which is slightly older but I am purposely keeping because it's the last version still having this neat feature:

<img width="960" alt="palemoon_ask_for_cookies_dialog" src="https://user-images.githubusercontent.com/37156979/99874587-68568c00-2ba6-11eb-859c-86e5f8131d27.png">

Obviously not all users may like this approach, so it should be made a configurable option.
Also, having such dialog popping up is no as intrusive as many might think. Because it shows up only for the first visit of any unique domain, and it's also a good way to remind me that I am visiting such site for the very first time.

**Comment by craigmiskell** [comment]
Yeah, i used to use that functionality myself and was rather annoyed when they removed it.

Sadly though, the WebExtension API does not allow for any such functionality.  At best we could open a HTML-based popup window (if FF's popup blocked doesn't get involved), but there's no way to make it modal and require a response in the way that the built-in functionality did, so it would be super janky and possibly unusable.

Sorry about that.

**Comment by smihaila** [comment]
Ok, then fuck firefox and its imbecile extension system and mentality. I hate the multiprocess model anyway - as it is not mindful of system resources, and a memory hog.

And I'm switching back to using Pale Moon, because it rocks.
