### ISSUE TITLE
Now with FF 86.0, you might need to update cookiemaster

### ISSUE THREAD

**Issue by ArcticGems** [craigmiskell/cookiemaster#24]
Now with FF 86.0, you might need to update cookiemaster =
https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/

**Comment by craigmiskell** [comment]
I'm not sure there's going to be any changes necessary.  Anything cookiemaster does to headers (e.g. removing some cookies) is simply before the new isolation takes place, and won't be affected by it.  And https://github.com/craigmiskell/cookiemaster/blob/master/background.js#L420 already handles the firstPartyDomain attribute of the cookies when catching those set by Javascript not headers (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies#first-party_isolation, where Total Cookie Protection is an evolution of the First Party Isolation feature).

@ArcticGems Is there some specific interaction/problem you are thinking of that I haven't considered yet?

Actually with TCP and the other recent tracking protections, CookieMaster is almost redundant these days (at least for the reason I originally wanted it, which is to limit being easily tracked across the entire internet).
