### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by procoolheat** [craigmiskell/cookiemaster#25]
Is this functionality possible on Chrome? There is nothing like this for Chrome.  It likely is not but I had to ask.

**Comment by craigmiskell** [comment]
The codebase would *probably* mostly work on Chrome right now, maybe with some minor tweaks.  However:
1. I don't use Chrome regularly and don't have any personal motivation to do that work.
2. [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/) will make the core implementation somewhere between infeasible and impossible, and it'd have to be reactive only (delete cookies as soon after they are created as possible, but with no guarantees they haven't already been used/sent back on some intervening requests; site behaviour would be inconsistent, potentially weird, and generally confusing).  So there would be extremely limited lifetime in the ported extension if someone got it working now.
