### ISSUE TITLE
Blocking 4-part top-level domain even though added to whitelist

### ISSUE THREAD

**Issue by KyleKirkpatrick** [craigmiskell/cookiemaster#27]
![image](https://github.com/craigmiskell/cookiemaster/assets/13932008/c2bd714e-2959-40e3-a09f-3a91350ef414)

08/08/2023, 4:53:30 pm | INFO | 2461: Blocking first party cookie in header for login.my.gov.au
08/08/2023, 4:53:30 pm | INFO | 2461: Setting allOK to false  because .my.gov.au. was not allowed
08/08/2023, 4:53:30 pm | INFO | 2461: Blocking first party cookie in header for login.my.gov.au
08/08/2023, 4:53:30 pm | INFO | 2461: Setting allOK to false  because .my.gov.au. was not allowed

The following relevant entries are in the whitelist:

.my.gov.au
my.gov.au
login.my.gov.au
https://login.my.gov.au

CookieMaster Version 1.2.1
Firefox 115.0.3 (64-bit)

**Comment by craigmiskell** [comment]
Ahh, government login systems, the bane of my existence :)

I can replicate it easily enough; will take a closer look in the next couple of days to try and debug why (other than assuming that `Setting allOK to false because .my.gov.au. was not allowed` is probably where things have gone horribly wrong)

**Comment by craigmiskell** [comment]
@KyleKirkpatrick It's the trailing dots in `.my.gov.au.`; the cookies [RFC](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.2.3) allows for ignoring leading dots which is handled by cookiemaster already, but the trailing dot is new and exciting.

As a workaround, you can go to CookieMaster Settings, put "my.gov.au." (with the trailing dot; leading dot is optional and not required) in the "Website address:" field, and click "Add Site".  That worked for me, and I expect it will for you (may require a couple of reloads to get out of the interim broken state though).

I'll think about a code solution (seems trivial at first glance, but I need to think through implications), and hopefully release a new version soon.

**Comment by craigmiskell** [comment]
Submitted version 1.2.2 for review; assuming it is accepted, it should be available for updating in the next day or two.

**Comment by KyleKirkpatrick** [comment]
@craigmiskell Wow you're amazing. That was quick! Thank you so much for fixing my issue!
