### ISSUE TITLE
More readable logs

### ISSUE THREAD

**Issue by dcfou** [craigmiskell/cookiemaster#29]
Make easier to find blocked cookies into logs, either by a font/background color or using 'BLOCKED' instead of 'INFO' level keyword.

Thanks :)

**Comment by craigmiskell** [comment]
Made them bold, and they look pretty easy to identify now.  Will be in version 1.2.3 when it's approved

**Comment by dcfou** [comment]
Thanks :)
... but, I have updated to 1.2.3 and it doesn't seem to work, all domain names are bold whatever cookies are allowed or blocked.
