### ISSUE TITLE
What about local storage ?

### ISSUE THREAD

**Issue by Tuxicoman2** [craigmiskell/cookiemaster#3]
Hi,

Thanks for your project.

I wonder what you think about the many other ways to store user unique information on his browser like : local storage, indexdb, etc...

Is this also a problem as Javascript allows to get back and share information across domains?

**Comment by craigmiskell** [comment]
From a privacy perspective, they're slightly different, but not substantially:

- More data can be stored than can easily in cookies
- The storage is domain specific i.e. data stored for www.domain.com cannot be read directly by a page on domain.com, although there are iframe + message passing tricks to get around that.

Sadly, as I've noted in #2 there's no way I can find for a Web Extension to get involved in controlling those forms of storage, so it's kind of moot.
