### ISSUE TITLE
Allow to export/import or copy/paste "Sites allowed to set cookies" list for backup purpose

### ISSUE THREAD

**Issue by antistress** [craigmiskell/cookiemaster#5]
Hi,

It would be a good idea to allow user to backup its "Sites allowed to set cookies" list, especially since you can't copy/paste the list !
Or allow copying/pasting the said list.

Thank you very much for CookieMaster !

**Comment by craigmiskell** [comment]
Great idea!  I'll see what I can do in the next couple of weeks; I"m working on a bunch of other changes right now, and should be able to slip this in.

**Comment by MichaelMeier99** [comment]
Thank you so much for this best of all Add-ons.
This is a really great idea! 
I have a long list of "allowed" sites in my firefox configuration. To import them with one click, would be amazing.

**Comment by craigmiskell** [comment]
Just released version 1.1.0 which includes Backup and Restore buttons in the settings page (which you can get to from the window popup icon now too).

**Comment by antistress** [comment]
Thanks  for that :)
