### ISSUE TITLE
Get in sync with cookie managment of firefox 68+ from i menue

### ISSUE THREAD

**Issue by bitstreamout** [craigmiskell/cookiemaster#6]
On clicking on of the i menue beside the URL I see below `Cookie' -> `Cookie and site Data' a few more cookies and for ebay I had to enable some of them.  I could not do this with cookiemaster as those had not been shown there

**Comment by craigmiskell** [comment]
I'm sorry, I don't understand what the issue is that you're reporting.  Can you show some screenshots of the issue occurring, and explain what you expected to happen that wasn't happening?
