### ISSUE TITLE
Suggestion for visual status on Cookiemaster button

### ISSUE THREAD

**Issue by ArcticGems** [craigmiskell/cookiemaster#7]
Here is a quick suggestion for how the Cookiemaster button's visual status should look.

Want something changed? Otherwise I can post all the .png files (or GIMP .xcf if you prefer).

Image that illustrate my suggestion  has been uploaded to ImgBB =
https://i.ibb.co/tbfC2H2/Show-ready.png

I used GIMP 2.10.12 for this =

Icon Size = 96x96px
Dot (selection) = 41x41px
Dot Bottom-Left (FROM BORDER) = B1px,L0px
Dot Bottom-Right (FROM BORDER) = B1px,R1px
Dot Border = paintbrush size 5, hardness 70, color black
Red (HTML) = a00505
Green (HTML) = 0a7e05
Blue (HTML) = 0521bd
Black (HTML) = 000000
White (HTML) = d8d8d8

**Comment by craigmiskell** [comment]
Thanks, these look much better than what I've done.  The .xcf would be ideal, as a source for any future modifications.

**Comment by ArcticGems** [comment]
@craigmiskell 
There are 4 versions (GIMP .xcf) in the zip file (I like 'round corners **half**-square' version the most!).

v1 = What you seen before.
v3 = The color dots has 2 color hue's (example: green & light green). I think v3 is better than v1.

(edited) Round corners square = Round corners square & has 2 color hue's (interesting alternative!).

(edited) Round corners **half**-square = Round corners square that is 'cut in half' &
has 2 color hue's (I like this one the most!).


Image that illustrate 'round corners square' version =
https://i.ibb.co/BC8ZtF6/cookies-96-show-rc-square.png

Image that illustrate 'round corners **half**-square' version =
https://i.ibb.co/fCTSj4t/cookies-96-show-32-rchs.png

All four versions has color dots/squares for 
temporary/session permissions (if you choose to implement it). =

Green/White = All allowed temporally.
Blue/White = Partly allowed temporally.

(edited) All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by ArcticGems** [comment]
@craigmiskell 
v3 is a fixed version of v2 (made an error with the temporary/session color dots).

(edited) All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by ArcticGems** [comment]
@craigmiskell 
I recommend to use the program PngOptimizer for these icons. 

File sizes are greatly reduced without loss off quality to the naked eye.

**Comment by ArcticGems** [comment]
@craigmiskell 
New version with 'round corners square', which is an interesting alternative!

Image that illustrate 'round corners square' version =
https://i.ibb.co/BC8ZtF6/cookies-96-show-rc-square.png

(edited) All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by ArcticGems** [comment]
@craigmiskell 
New version with 'round corners half-square' (based on the previous version),
which is another interesting alternative! (I like this one the most!).

Image that illustrate 'round corners half-square' version =
https://i.ibb.co/fCTSj4t/cookies-96-show-32-rchs.png

(edited) All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by craigmiskell** [comment]
I only have GIMP 2.8 currently, and it doesn't like XCF version 11; before I go down a rabbit hole of trying to get an upgraded version, is it possible to save the files as a backwards compatible version?

**Comment by ArcticGems** [comment]
> 
> 
> I only have GIMP 2.8 currently, and it doesn't like XCF version 11; before I go down a rabbit hole of trying to get an upgraded version, is it possible to save the files as a backwards compatible version?

@craigmiskell 
I have changed all .xcf files, from 'Normal Mode' to 'Legacy Mode',
so they should **work in GIMP 2.8.**

(If you are on Windows, you can easily upgrade to GIMP 2.10.12 just by running the install file)

Layers with 'vertical_line / verticalLine' in the layer name are
only used if you save icons for temporary/session permissions.

Temporary/session permissions uses 4 colors (in 4 layers), example =
BL-LightWhite
BL-white (actually light grey)
BL-Lightgreen
BL-green

----

BL = Bottom-Left
BR = Bottom-Right

```
Rectangle select tool =

For dark colors: size 84x41px, Ronded corners radius 19px,
position from image border left/right/bottom 1px.

For light colors: size 70x25px, Ronded corners radius 19px,
position center of the dark color.

Stroke selection: Stroke line, Solid color, Antialiasing enabled,
Line width 3px, black FG color (HTML 000000)

Half-square version: Cut (Edit->Clear) the rounded corners 
squares just before top-left/top-right corners starts.
```

(edited) All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by ArcticGems** [comment]
@craigmiskell 

A new **v2** of 'round corners **half**-square' version. 
**V2's** status colors has 3 hue's and lines has 2 hue's (best version IMO!!).

Image that illustrate the v2 of 'round corners half-square' version =
https://i.ibb.co/VHkTj3v/cookies-96-LEGACY-show-rc-half-square-v2.png

Zip file contains all 5 versions in 'Legacy Mode' (works in GIMP 2.8) and 
a .xcf that show the differences of v1 & v2 (toggle visibility of top/1st layer).
('show' file: cookies-96-LEGACY-show-rc_half_square-v2.xcf)

```
Rectangle select tool =

For darkest colors: size 84x41px, Ronded corners radius 19px,
position from image border left/right/bottom 1px.

For 'middle' colors: size 76x33px, Ronded corners radius 19px,
position center of the darkest color.

For lightest colors: size 70x25px, Ronded corners radius 19px,
position center of the darkest color.

1st 'round corners half-square' line (that follows status color edges) =
     Rectangle select tool: size 84x41px, Ronded corners radius 19px,
     position from image border left/right/bottom 1px.

     Stroke selection: Stroke line, Solid color, Antialiasing enabled,
     Line width 3px, FG color (HTML 000000)

2nd 'round corners half-square' line =
     Rectangle select tool: size 82x39px, Ronded corners radius 19px,
     position from image border left/right/bottom 2px.

     Stroke selection: Stroke line, Solid color, Antialiasing enabled,
     Line width 2px, FG color (HTML 1e1e1e)

    Cut (Edit->Clear) in order to remove 1px of the '2nd' line inside.

Cut (Edit->Clear) the rounded corners squares (status colors & lines) just 
before top-left/top-right corners starts.

Use 'Rectangle select tool' to create two 84x1px lines (HTML 000000 & 1e1e1e) and
place them on top of 1st/2nd 'round corners half-square' lines so they connect.

```
(edited) All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by ArcticGems** [comment]
@craigmiskell 

I made a new  **round** cookie with simplistic design from scratch (Really like this one!)!!

Size 192x192px in 'Legacy Mode' (works in GIMP 2.8).

You also use allow/block icons that are to the left in the pop-up when you change permission,
which is why I added 2 layers with a allow symbol and a block symbol.

The .zip file includes a .xcf where I made the allow/block symbols =
filename: Cookie-192-LEGACY-AllowBlock.xcf

Image that illustrate the new  **round** cookie with simplistic design =
https://i.ibb.co/7KtjHB7/Cookie-192-LEGACY-simplistic-round-v1.png

Make your edits in 192x192px, then save png's in 96x96px (or 128x128px even).

All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf  =
http://depositfiles.com/files/4qxj4k05c

**Comment by B0lt-Burst** [comment]
> 
> 
> I made a new **round** cookie with simplistic design from scratch (Really like this one!)!!
> 
> All **6** versions in 'Legacy Mode' (works in GIMP 2.8), a show .xcf and allow/block .xcf =
> http://depositfiles.com/files/4qxj4k05c

Well done!! I hope @craigmiskell choose this one!

**Comment by craigmiskell** [comment]
Thanks @ArcticGems.
I'm just in the middle of moving between cities/houses, and will be a bit busy for a couple more weeks, but I love your work and will be updating Cookiemaster with these as soon as I can.  I too like the simple round version, I just need to choose between the variations.

**Comment by ArcticGems** [comment]
@craigmiskell 

I have created a new variation of my latest submission: 
**Round** cookie with improved color **dots** (yes, I brought the color dots back again).

Reminder:
**Left** color dot   = **1st** party permission state.
**Right** color dot = **3rd** party permission state.

Image that shows all 8 versions in 3 backgrounds with different brightness,
so that you can get a better 'feeling' for them (number list below that explains this image)=
https://i.ibb.co/Mp8SpGb/Cookie-show-8-version.png

1. New **round** cookie with simplistic design made from scratch!
Size: 192x192px
Filename: Cookie-192-LEGACY-simplistic_round-v1.xcf

2. **Round** cookie with improved color **dots** (based on nr 1, 4 & 7).
Size: 192x192px
Filename: Cookie-192-LEGACY-simplistic_round-ColorDots.xcf

3. My first submission from way back: original **square** cookie with **old** single hue 'color dots'.
Size: 96x96px
Filename: cookies-96-LEGACY-v1.xcf

4. Verion 3 of my first submission: original **square** cookie with **old** 2 hue's color dots.
Size: 96x96px
Filename: cookies-96-LEGACY-v3.xcf

5. Original **square** cookie with rounded corners rectangle with 2 hue's color status.
Size: 96x96px
Filename: cookies-96-LEGACY-round_corners_square.xcf

6. Original **square** cookie with rounded corners **half**-rectangle with 2 hue's color status.
Size: 96x96px
Filename: cookies-96-LEGACY-round_corners_half_square.xcf

7. Original **square** cookie with rounded corners **half**-rectangle with 
**3** hue's color status and lines with **2** hue's.
Size: 96x96px
Filename: cookies-96-LEGACY-round_corners_half_square-v2.xcf

8. **Round** cookie with **light** colors and improved color **dots** (based on nr 2).
Size: 192x192px
Filename: Cookie-192-LEGACY-simplistic_round-ColorDots-LIGHT.xcf


(edited) '**Round** cookie with improved color **dots**' (light & dark variations: nr 2 & 8) =
(check my previous post in case you have not downloaded variations nr 1 & 3-7)
http://depositfiles.com/files/xl3b1kc9f

**Comment by B0lt-Burst** [comment]
> 
> 
>     2. **Round** cookie with improved color **dots** (based on nr 1, 4 & 7).
>        Size: 192x192px
>        Filename: Cookie-192-LEGACY-simplistic_round-ColorDots.xcf
>

Nice, I vote for nr.2 on this list! **+1**
https://imgsafe.org/image/4ee3226602

**Comment by ArcticGems** [comment]
I have added a lighter variation of nr 2 = nr 8

Check my post above = https://github.com/craigmiskell/cookiemaster/issues/7#issuecomment-541434918

**Comment by B0lt-Burst** [comment]
> 
> 
> I have added a lighter variation of nr 2 = nr 8
> 
> Check my post above = [#7 (comment)](https://github.com/craigmiskell/cookiemaster/issues/7#issuecomment-541434918)

Hmm... hard to choose between 2 & 8. I wonder what @craigmiskell will choose.

**Comment by ArcticGems** [comment]
@craigmiskell 
So which one did you choose? Do you want me to change something?.

**Comment by craigmiskell** [comment]
Hi @ArcticGems 
I really like version 8, and will look at integrating them today.

What FOSS license would you be willing to license these under?

**Comment by ArcticGems** [comment]
> 
> 
> Hi @ArcticGems
> I really like version 8, and will look at integrating them today.
> 
> What FOSS license would you be willing to license these under?

@craigmiskell 
I'm fine with Creative Commons CC0
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by B0lt-Burst** [comment]
> 
> I really like version 8, and will look at integrating them today.

Great choice @craigmiskell ! 

I hope Cookiemaster gets updated soon! :+1:

**Comment by craigmiskell** [comment]
You'll  to bear with me for a few days; I haven't looked at some of this code for a long time, and as I remind myself how it works and look to keeping it performant (because it will have to keep the icon up to date, rather than waiting for the user to actively choose to open the popup), I'm finding I'm having to rewrite chunks of the data handling.  It'll be better when I'm done, but it's taking a while.

**Comment by B0lt-Burst** [comment]
Any progress? :+1:

**Comment by craigmiskell** [comment]
Only slow; I've had various things to deal with, including being a bit sick the last week.  I have 2 weeks off soon though (over the Christmas/New Year season), so I should be able to finish up then, if I don't get to it before.  Hopefully there will be a nice shiny release in the early new year at the latest.

**Comment by MichaelMeier99** [comment]
Hi Craig,

 

 

I shifted your data into the friends zone. Hope, you are well again!

It took me until now to find your mails.

I asked myself many times: What may have happened? Smile.

 

 

Warm regards and happy holiday!

irene

 

Gesendet: Samstag, 07. Dezember 2019 um 23:40 Uhr
Von: "craigmiskell" <notifications@github.com>
An: craigmiskell/cookiemaster <cookiemaster@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [craigmiskell/cookiemaster] Suggestion for visual status on Cookiemaster button (#7)


Only slow; I've had various things to deal with, including being a bit sick the last week. I have 2 weeks off soon though (over the Christmas/New Year season), so I should be able to finish up then, if I don't get to it before. Hopefully there will be a nice shiny release in the early new year at the latest.

**Comment by craigmiskell** [comment]
Quick update: I didn't get as far as I wanted over my break, for various reasons, but the most relevant is that as I refactored the code to be more resilient I kept on finding problems; if not bugs, then at least things that didn't sit right (e.g. handling of first-party cookies in iframes, where current versions use the allow/deny settings in CookieMaster but don't report those cookies as allowed/blocked in the popup, but with the visual status badges it becomes much more obvious)

Also the vexing problem of correctly categorising cookies set by javascript came up again (the cookies.onChanged event only says that the cookie changed, not which tab it came from) and I got a annoyed with that (again) and lost motivation for a while.

But then I was peeling potatoes for dinner one night and had an idea about hooking the `document.cookies` property, and then found https://stackoverflow.com/questions/32410331/proxying-of-document-cookie.  I've just now managed to get a prototype bit of code to hook that using web extension content-scripts and send runtime messages to the background script, which means I will be able to positively correlate cookies being set with the actual tab they came from, rather than having to guess.

The *downside* is that this will send me down a rabbit hole for a while refactoring a bit again (and ripping out some complicated code that will be no longer necessary).  This will take me some time still, I'm sorry, but the end result is going to be *much* better.

**Comment by ArcticGems** [comment]
ok, no problem! I'm happy that you have made some progress. :smiley:  :+1:

**Comment by craigmiskell** [comment]
Implementation is complete!  Just going to crack out a couple of other requests while I'm going hot, and then release it.  Should be within a week.

**Comment by craigmiskell** [comment]
Submitted it to addons.mozilla.org.  Undergoing review now, unsure if it'll pass automatically or require a person to look at it.  I had some unrelated issues with a 3rd party library in 1.0.9 that may cause it to require manual review this time.  But with luck, the new version should be available very shortly

**Comment by craigmiskell** [comment]
And there it goes, already available.  Have at it!
