### ISSUE TITLE
Visual status doesn't show if NoScript blocks JavaScript

### ISSUE THREAD

**Issue by ArcticGems** [craigmiskell/cookiemaster#9]
Just tested the latest update! :+1: :smile: :tada: 

I discovered a bug. If NoScript blocks a individual website JavaScripts,
then Cookiemaster can't show visual status on that site. 

When I enable the individual website JavaScripts, then the visual status works.

If I disable JavaScripts again, visual status stop working. 

Seems to apply to all sites where NoScript blocks JavaScripts.

**Comment by craigmiskell** [comment]
Yes, that seems likely.  To get more reliable detection of cookies set by javascript, I had to add a content script that hooks into it.  I imagine it's failing fairly early on.  I'll see what I can do, but I can't promise I can fix it.

**Comment by craigmiskell** [comment]
I cannot immediately replicate the problem, even setting the domain to 'untrusted'.  I don't normally use No Script; can you confirm which exact add-on you're using (I tried "No Script Security Suite").  A link to the add-on page would be best, so I can be 100% sure I'm using the same one.

**Comment by craigmiskell** [comment]
Also a screenshot of exactly what you see might be helpful.

**Comment by ArcticGems** [comment]
NoScript = https://addons.mozilla.org/en-US/firefox/addon/noscript/

Example =

**Top:** JavaScript blocked, shows only cookie icon (no visual status/color dot)
**Bottom:** JavaScript allowed/trusted, shows visual status (color dot)
https://i.ibb.co/896fHf6/bug-Noscript2.jpg

**Comment by craigmiskell** [comment]
Ohhh, that's not a bug, the indicator is showing exactly what's going on.

Cookies can be set in two different ways:
1. In headers as part of the HTTP request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie)
1. From executing javascript (https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

So disabling javascript on a page isn't preventing cookiemaster from showing an indicator, it means that the javascript which is setting the cookie isn't executing in the first place, so there's nothing for cookie-master to notice/report.

**Comment by ArcticGems** [comment]
hmm, ok.

But this could confuse some users, so could you add a tooltip that says (for Cookiemaster button when there is **no** color dot) =

> "No cookies (Either the site has none OR blocked by a addon e.g. NoScript)"
